spring.application.name=hff_data_studio
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/hff_data_studio_db
spring.datasource.username=postgres
spring.datasource.password=Pa$$Na$$aIW0rd
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=your-256-bit-secret-key-for-jwt-signing-please-change-in-production
jwt.expiration-time=900000
jwt.refresh-expiration=604800000
file.upload-dir=./uploads
file.max-size=20MB
cors.allowed-origins=http://localhost:3000,http://localhost:3031